# Generated by Django 2.1.15 on 2022-01-19 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagement', '0006_auto_20220119_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_addr', models.CharField(max_length=20, unique=True, verbose_name='MAC地址')),
                ('is_online', models.BooleanField(default=False, verbose_name='是否在线')),
                ('cur_status', models.CharField(default='', max_length=32, verbose_name='当前状态')),
                ('user_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.User', verbose_name='从属用户')),
            ],
        ),
        migrations.CreateModel(
            name='MachineData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200, verbose_name='设备数据')),
                ('upload_time', models.CharField(max_length=100, verbose_name='设备采集时间')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Machine', verbose_name='设备')),
            ],
        ),
    ]
