# Generated by Django 2.1.15 on 2022-01-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_auto_20220119_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': '硬件设备', 'verbose_name_plural': '硬件设备'},
        ),
        migrations.AlterModelOptions(
            name='machinedata',
            options={'verbose_name': '设备数据', 'verbose_name_plural': '设备数据'},
        ),
        migrations.AlterModelTable(
            name='machine',
            table='machine_info',
        ),
        migrations.AlterModelTable(
            name='machinedata',
            table='machine_data',
        ),
    ]
