# Generated by Django 2.1.15 on 2022-01-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_auto_20220119_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='work_type',
            field=models.CharField(choices=[('1', 'Light'), ('2', 'temp&humidity')], default='', max_length=10),
        ),
    ]
