# Generated by Django 2.1.15 on 2022-01-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0005_auto_20220120_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinedata',
            name='cur_status',
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(default='我的设备', max_length=20, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='work_type',
            field=models.CharField(choices=[('1', 'light'), ('2', 'dht11')], default='', max_length=10, verbose_name='设备类型'),
        ),
    ]
