# Generated by Django 2.1.15 on 2022-01-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_auto_20220125_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Machine', verbose_name='设备')),
            ],
            options={
                'verbose_name': '命令历史',
                'verbose_name_plural': '命令历史',
                'db_table': 'machine_command_history',
            },
        ),
    ]
