# Generated by Django 2.1.15 on 2022-01-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0007_commandhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandhistory',
            name='command',
            field=models.CharField(default='', max_length=20, verbose_name='指令内容'),
        ),
    ]
