# Generated by Django 2.1.15 on 2022-01-31 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_auto_20220119_1539'),
        ('Data', '0008_commandhistory_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=32, verbose_name='发送时间')),
                ('text', models.TextField(max_length=255, verbose_name='内容')),
                ('content_type', models.CharField(max_length=10, verbose_name='类型')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='UserManagement.User', verbose_name='发送方')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='UserManagement.User', verbose_name='接收方')),
            ],
            options={
                'verbose_name': '聊天历史',
                'verbose_name_plural': '聊天历史',
                'db_table': 'chat_history',
            },
        ),
    ]
