# Generated by Django 2.1.15 on 2022-01-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0009_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='from_type',
            field=models.TextField(default='', max_length=10, verbose_name='发送类型'),
        ),
    ]
