# Generated by Django 2.1.15 on 2022-01-31 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_service'),
        ('Data', '0010_chathistory_from_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='to_user',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Service', verbose_name='客服'),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='from_type',
            field=models.TextField(default='', max_length=10, verbose_name='发送方类型'),
        ),
    ]
