# Generated by Django 2.1.15 on 2022-02-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0011_auto_20220131_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(default='', max_length=10, verbose_name='触发条件')),
                ('condition_num', models.IntegerField(default=0, verbose_name='触发阈值')),
                ('command', models.CharField(default='', max_length=10, verbose_name='设备命令')),
                ('command_num', models.IntegerField(default=0, verbose_name='执行幅度')),
                ('lower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lower', to='Data.Machine', verbose_name='下位机')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper', to='Data.Machine', verbose_name='上位机')),
            ],
            options={
                'verbose_name': '设备联动',
                'verbose_name_plural': '设备联动',
                'db_table': 'machine_link',
            },
        ),
    ]
