# Generated by Django 2.1.15 on 2022-02-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0012_machinelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelink',
            name='data_item',
            field=models.TextField(default='', max_length=24, verbose_name='数据项'),
        ),
    ]
