# Generated by Django 2.2 on 2022-03-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0013_machinelink_data_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
