# Generated by Django 2.2 on 2022-04-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0016_banip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='service',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Service', verbose_name='客服'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='machine',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Data.Machine', verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='user_belong',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.User', verbose_name='从属用户'),
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='machine',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Data.Machine', verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='machinelink',
            name='lower',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='lower', to='Data.Machine', verbose_name='下位机'),
        ),
        migrations.AlterField(
            model_name='machinelink',
            name='upper',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='upper', to='Data.Machine', verbose_name='上位机'),
        ),
    ]
