# Generated by Django 2.1.15 on 2022-01-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Essay', '0002_auto_20220108_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='good',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
