# Generated by Django 2.1.15 on 2022-01-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_auto_20220119_1539'),
        ('Essay', '0003_essay_good'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Essay.Essay', verbose_name='点赞文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.User', verbose_name='点赞用户')),
            ],
        ),
    ]
