# Generated by Django 2.1.15 on 2022-01-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Essay', '0004_goodlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodlist',
            options={'verbose_name': '文章点赞记录', 'verbose_name_plural': '文章点赞记录'},
        ),
        migrations.AlterModelTable(
            name='goodlist',
            table='essay_good_list',
        ),
    ]
