# Generated by Django 2.1.15 on 2022-01-21 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_auto_20220119_1539'),
        ('Essay', '0005_auto_20220121_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('ip', models.CharField(max_length=25, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '文章浏览记录',
                'verbose_name_plural': '文章浏览记录',
                'db_table': 'essay_browse_history',
            },
        ),
        migrations.RemoveField(
            model_name='essay',
            name='good',
        ),
        migrations.AddField(
            model_name='browsehistory',
            name='essay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Essay.Essay', verbose_name='浏览文章'),
        ),
        migrations.AddField(
            model_name='browsehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.User', verbose_name='用户'),
        ),
    ]
