# Generated by Django 2.1.15 on 2022-01-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Essay', '0006_auto_20220121_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaycommentreply',
            name='good_num',
            field=models.IntegerField(default=0, verbose_name='点赞量'),
        ),
    ]
