# Generated by Django 2.1.15 on 2022-01-21 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_auto_20220119_1539'),
        ('Essay', '0007_essaycommentreply_good_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaycommentreply',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_to', to='UserManagement.User', verbose_name='回复谁'),
        ),
        migrations.AlterField(
            model_name='essaycommentreply',
            name='from_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Essay.EssayComment', verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='essaycommentreply',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_from', to='UserManagement.User', verbose_name='发表用户'),
        ),
    ]
