# Generated by Django 2.2 on 2022-04-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Essay', '0011_essay_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsehistory',
            name='essay',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Essay.Essay', verbose_name='浏览文章'),
        ),
        migrations.AlterField(
            model_name='browsehistory',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserManagement.User', verbose_name='上传用户'),
        ),
        migrations.AlterField(
            model_name='essaycollection',
            name='essay',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Essay.Essay', verbose_name='收藏文章'),
        ),
        migrations.AlterField(
            model_name='essaycollection',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='essaycomment',
            name='from_essay',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Essay.Essay', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='essaycomment',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserManagement.User', verbose_name='发表用户'),
        ),
        migrations.AlterField(
            model_name='essaycommentreply',
            name='from_comment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Essay.EssayComment', verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='essaycommentreply',
            name='reply_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='UserManagement.User', verbose_name='回复谁'),
        ),
        migrations.AlterField(
            model_name='essaycommentreply',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_from', to='UserManagement.User', verbose_name='发表用户'),
        ),
        migrations.AlterField(
            model_name='goodlist',
            name='essay',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Essay.Essay', verbose_name='点赞文章'),
        ),
        migrations.AlterField(
            model_name='goodlist',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.User', verbose_name='点赞用户'),
        ),
    ]
