"""
Django settings for MyHouse project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
# import pymysql
# pymysql.version_info = (1, 3, 13, "final", 0)  # 解决mysql版本问题报错而添加的代码
# pymysql.install_as_MySQLdb()
import MySQLdb
import secure


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secure.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*', ]

# allow websocket
WEBSOCKET_ACCEPT_ALL = True
# WEBSOCKET_FACTORY_CLASS = 'dwebsocket.backends.uwsgi.factory.uWsgiWebSocketFactory'

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 插件
    'corsheaders',  # 解决跨域
    # 'dwebsocket',   # 即时通信，直接使用，不需要安装
    'gunicorn',  # gunicorn服务器
    'ckeditor',     # 后台,富文本
    'ckeditor_uploader',  # 后台,富文本上传
    'silk',  # 性能监测
    'haystack',  # 全文检索框架
    # 自定义
    'UserManagement',  # 用户管理
    'Data',  # 数据管理
    'Essay',  # 文章管理
]

# 设置跨域可用
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = (secure.BACKEND_URL+":*", )

SESSION_COOKIE_SAMESITE = None  # response header set-cookie:samesite=lax  Default: 'Lax'
CSRF_COOKIE_SAMESITE = None

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)

CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 解决同源
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF防护中间件
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'dwebsocket.middleware.WebSocketMiddleware',
    'silk.middleware.SilkyMiddleware',  # 性能监测
    'MyHouse.middleware.BanIp',  # 自定义过滤中间件
]

PASSWORD_HASHERS = (
    'django.contrib.auth.hashers.MD5PasswordHasher',  # 加密算法
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.SHA1PasswordHasher',
    'django.contrib.auth.hashers.CryptPasswordHasher',
)

ROOT_URLCONF = 'MyHouse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyHouse.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', #设置为mysql数据库
        'NAME': secure.mysql_conn['db_name'],  #mysql数据库名
        'USER': secure.mysql_conn['user'],  #mysql用户名
        'PASSWORD': secure.mysql_conn['password'],   #mysql密码
        'HOST': secure.mysql_conn['host'],  #留空默认为localhost
        'PORT': secure.mysql_conn['port'],  #留空默认为3306端口
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://:{secure.redis_conn['password']}@{secure.redis_conn['host']}:{secure.redis_conn['port']}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_REDIS_ALIAS = "default"

REDIS_HOST = secure.redis_conn['host']
REDIS_PORT = secure.redis_conn['port']
REDIS_PASSWORD = secure.redis_conn['password']

HAYSTACK_CONNECTIONS = {
    "default":{
        # "ENGINE": "haystack.backends.whoosh_backend.WhooshEngine",  # 使用whoosh引擎
        "ENGINE": "Essay.whoosh_cn_backend.WhooshEngine",  # 使用whoosh引擎
        "PATH": os.path.join(BASE_DIR, "whoosh_index"),  # 索引文件路径
    }
}
#设置分页显示的数据量
HAYSTACK_SEARCH_RESULTS_PER_PAGE = secure.essay_count['essay_count_each_search_page']
# 添加、修改、删除数据时，自动生成索引
HAYSTACK_SINGAL_PROCESSOR = "haystack.signals.RealtimeSignalProcessor"

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# debug=False 设置静态文件的保存目录
STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # debug=False生效
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]  # debug=True生效

STATIC_URL = '/static/'

MEDIA_URL = '/upload_files/'  # 你的media url 在Url显示并没什么关系

MEDIA_ROOT = secure.MEDIA_ROOT

# ckeditor配置
CKEDITOR_JQUERY_URL = 'https://cdn.bootcdn.net/ajax/libs/jquery/2.1.4/jquery.min.js'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',  # 工具栏全部功能
        'extraPlugins': 'codesnippet',
        'height': 500,  # 高度
        'width': 730,  # 宽度
    },
}
# 他的目录相对与media root 就是 media root + CKEDITOR_UPLOAD_PATH 不能写成"/uploads/"
CKEDITOR_UPLOAD_PATH = "admin/ckeditor/"
CKEDITOR_IMAGE_BACKEND = 'pillow'

# silk 性能监测
SILKY_PYTHON_PROFILER = True
# 生成.prof文件，silk产生的程序跟踪记录，详细记录来执行来哪个文件，哪一行，用了多少时间等信息
SILKY_PYTHON_PROFILER_BINARY = True
# .prof文件保存路径（最好不要像我这样设置在项目目录中）
# 如果没有本设置，prof文件将默认保存在MEDIA_ROOT里
SILKY_PYTHON_PROFILER_RESULT_PATH = secure.SILKY_PYTHON_PROFILER_RESULT_PATH
# 认证需要自己写
SILKY_AUTHENTICATION = True  # User must login
SILKY_AUTHORISATION = True  # User must have permissions  # from django.contrib.auth.models import User as admin
SILKY_PERMISSIONS = lambda user: user.is_superuser

# 邮件配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = secure.email_setting["EMAIL_HOST"]
EMAIL_PORT = 25
EMAIL_HOST_USER = secure.email_setting["EMAIL_HOST_USER"]
EMAIL_HOST_PASSWORD = secure.email_setting["EMAIL_HOST_PASSWORD"]
EMAIL_USE_TLS = True  # 这里必须是 True，否则发送不成功

# 头像大小限制
PHOTO_SIZE = 3*1024*1024
PHOTO_TYPE = ["png", "jpg", "gif"]

# 后端域
BACKEND_SITE = f"{secure.BACKEND_URL}:{secure.BACKEND_PORT}"

# MQTT服务器相关
MQTT_SERVER_HOST = secure.mqtt_conn["MQTT_SERVER_HOST"]
MQTT_SERVER_PORT = secure.mqtt_conn["MQTT_SERVER_PORT"]
MQTT_USERNAME = secure.mqtt_conn["MQTT_USERNAME"]
MQTT_PASSWORD = secure.mqtt_conn["MQTT_PASSWORD"]

# 文章列表，一页几个
essay_count_each_search_page = secure.essay_count['essay_count_each_search_page']
# 文章推荐，一栏几个
essay_link_each_recommend = secure.essay_count['essay_link_each_recommend']
# 文章评论，一页几个
comment_each_page = secure.essay_count['comment_each_page']
# 个人主页，历史记录，一页几个
personal_info_count_per_page = secure.essay_count['personal_info_count_per_page']
