# Generated by Django 2.1.15 on 2022-01-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
