# Generated by Django 2.1.15 on 2022-01-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_auto_20220106_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverify',
            name='aim',
            field=models.CharField(choices=[('r', '用户注册'), ('c', '密码修改')], default='r', max_length=20),
        ),
    ]
