# Generated by Django 2.1.15 on 2022-01-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_emailverify_aim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='aim',
            field=models.CharField(choices=[('r', '用户注册'), ('c', '密码修改')], default='r', max_length=20, verbose_name='用途'),
        ),
    ]
