# Generated by Django 2.1.15 on 2022-01-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_photo',
            field=models.ImageField(blank=True, default='head_photo/defaultHead.png', null=True, upload_to='head_photo/', verbose_name='头像'),
        ),
    ]
