# Generated by Django 2.2 on 2022-03-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0008_auto_20220205_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=32, verbose_name='发送时间')),
                ('text', models.TextField(max_length=255, verbose_name='内容')),
                ('content_type', models.CharField(max_length=10, verbose_name='类型')),
                ('from_type', models.TextField(default='', max_length=10, verbose_name='发送方类型')),
                ('service', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Service', verbose_name='客服')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '聊天历史',
                'verbose_name_plural': '聊天历史',
                'db_table': 'chat_history',
            },
        ),
    ]
